### ISSUE TITLE
[BUG] No pasa nada luego de darle explorar

### ISSUE THREAD

**Issue by ivanvelasquezabril** [ConsiliumBots/icfesbot-2022-issue-tracker#1]
Problema con el flujo. Al darle explorar mas no pasa nada 

![image](https://user-images.githubusercontent.com/64808378/188496593-3b97217c-8efa-4539-813d-275c706f691d.png)

**Comment by PipoLiz** [comment]
Las recomendaciones podrían afinarse más. 

![WhatsApp Image 2022-09-05 at 12 53 59 PM](https://user-images.githubusercontent.com/87825021/188497735-c8892458-15ac-4f3a-8146-3c105905cb89.jpeg)
![WhatsApp Image 2022-09-05 at 12 54 23 PM](https://user-images.githubusercontent.com/87825021/188497739-8da440c8-328e-4388-b6a6-d6dd3527dbfc.jpeg)

**Comment by acarril** [comment]
> Las recomendaciones podrían afinarse más.
> 
> ![WhatsApp Image 2022-09-05 at 12 53 59 PM](https://user-images.githubusercontent.com/87825021/188497735-c8892458-15ac-4f3a-8146-3c105905cb89.jpeg) ![WhatsApp Image 2022-09-05 at 12 54 23 PM](https://user-images.githubusercontent.com/87825021/188497739-8da440c8-328e-4388-b6a6-d6dd3527dbfc.jpeg)

Esto es un tema diferente del original; favor ponerlo en un issue separado.

**Comment by acarril** [comment]
> Las recomendaciones podrían afinarse más.

Esto es un tema diferente del original; favor ponerlo en un issue separado.

**Comment by acarril** [comment]
> Problema con el flujo. Al darle explorar mas no pasa nada

Cuando el bot termina en _WIP_ significa _work in progress_, entonces no es un problema, si no que aún no se ha implementado lo que sigue.

**Comment by PipoLiz** [comment]
En la siguiente imagen se ve que no hay más info, ¿está bien? 
![WhatsApp Image 2022-09-05 at 1 03 47 PM (1)](https://user-images.githubusercontent.com/87825021/188499067-eefd32af-1d38-4326-a575-8ab7dcc99084.jpeg)
