### ISSUE TITLE
Faltan programas TyT relacionados con gastronomía, culinaria, cocina...

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#12]
## Contexto
![image](https://user-images.githubusercontent.com/87825021/192558418-0116846c-8775-4f89-8dd5-696992830d31.png)

En la imagen se pueden ver que el SNIES considera programas relacionados con gastronomía, culinaria, cocina. 

Con el bot hay problemas en encontrar un programa TyT relacionado con gastronomía, culinaria, cocina... No muestra opciones afines y luego vuelve al inicio.

## Propuesta
Se debe hacer un esfuerzo por presentar un listado más completo de opciones con "palabras clave" para que el estudiante pueda encontrar programas afines a sus intereses. De lo contrario, si se deja sólo por núcleos básicos del conocimiento (que es como creo está ahora), se presentan opciones demasiado genéricas para que el estudiante pueda realmente conocer la diversidad de los 700 programas en ES que se mencionan al inicio

## Canal

- [x] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by acarril** [comment]
Esto está relacionado a #24, y respuesta es la misma que [esta](https://github.com/ConsiliumBots/icfesbot-2022-issue-tracker/issues/24#issuecomment-1267403555). Básicamente, no hemos podido reproducir el problema de no encontrar carreras que sí existen en SNIES.

@PipoLiz menciona un problema relacionado que es que el recomendador no ofrece opciones de instituciones técnicas/tecnológicas. Esto es una [mejora que tenemos que hacer al recomendador](https://github.com/ConsiliumBots/brains-recommender/issues/9), pero va más allá del scope de este issue.

**Comment by PipoLiz** [comment]
Hola @acarril. Si, se relaciona como mencionas con el #24, continuemos la discusión allí. Gracias.
