### ISSUE TITLE
Comentarios relacionados con el flujo.

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#13]
## Contexto

A continuación se pueden observar algunos de los comentarios para el flujo, se dejan aquí para darle seguimiento. 

![image](https://user-images.githubusercontent.com/87825021/192560198-4f393f05-47d6-4ee8-8c7e-242bf6559412.png)
![image](https://user-images.githubusercontent.com/87825021/192560242-7e1a1761-45e2-48d7-a81b-d582de495679.png)
![image](https://user-images.githubusercontent.com/87825021/192560269-b8456301-4361-46aa-a3e8-1f19efd7f3ef.png)
![image](https://user-images.githubusercontent.com/87825021/192560304-2c78a6f0-f673-4d14-8601-517c2495c23a.png)

## Canal

- [ ] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by PipoLiz** [comment]
Sería bueno incluir información relevante en "conocer más sobre la carrera", como duración, valor de la matrícula, acreditación, modalidad. Tal como está el diseño por ahora, veo más fácil que un estudiante encuentre esta información más completa en SNIES.

**Comment by PipoLiz** [comment]
![image](https://user-images.githubusercontent.com/87825021/192563945-fdc671c8-4b71-4c75-bbbd-70bd20b68ecc.png)

**Comment by jcechavarri** [comment]
> Todos tienen cédula? Ajustar a otros tipos de ID

Cambiado a nr de documento, como fue sugerido en #22 

> Y si ya tomó Saber 11 y conoce el puntaje? Reformular la pregunta

Solo se hace la pregunta cuando no tenemos su puntaje. 

> Aquí creo que el término adecuado sería programa y no carrera

Se hizo el cambio 👍🏼 

> La mayoría o en promedio?

El promedio, se hace el cambio.

> Sería bueno incluir información relevante en "conocer más sobre la carrera", como duración, valor de la matrícula, acreditación, modalidad. Tal como está el diseño por ahora, veo más fácil que un estudiante encuentre esta información más completa en SNIES.

Quedará en otra _issue_.

> ¿Y si el estudiante no conoce o no tiene Sisben IV, no puede seguir interactuando opciones de financiación? Tal vez sería bueno incluir el link del Sisben para consultarlo...

Solucionado.
