### ISSUE TITLE
[BUG] No se inicia el chat 

### ISSUE THREAD

**Issue by santivelasquezb1** [ConsiliumBots/icfesbot-2022-issue-tracker#15]
## Describe el problema
Al entrar al link, no se inicia ninguna interaccion ni aparece ninguna forma para interactuar. Aun despues de recargar la pagina varias veces. El navegador que estoy usando es google Chrome desde windows

## Comportamiento esperado
Deberia haber alguna sugerencia sobre que hacer, o el bot deberia comenzar a interactuar sobre si se quiere saber mas sobre educacion.

## Screenshots
![image](https://user-images.githubusercontent.com/110130849/192606297-a938245c-4760-4861-b987-901dd6961de1.png)

## Canal

- [x] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by PipoLiz** [comment]
Persiste el problema, Se puede superar con varios F5 o equivalentes, pero esa solución puede llevar a pérdidas de interacciones.
