### ISSUE TITLE
Mejorar las recomendaciones de carrera 

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#16]
## Contexto

![image](https://user-images.githubusercontent.com/87825021/192617413-db78ea40-21e4-443e-947c-74f4c8e88cb0.png)
![image](https://user-images.githubusercontent.com/87825021/192617398-1b04d5fd-b04c-4b97-8cc0-79f584a31c85.png)

Se podría mejorar las recomendaciones de carrera. Por ejemplo, para una persona que expresa interés en Economía, administración, contaduría y afines, tal vez existan recomendaciones afines más certeras que programas en Actividad física y deporte, Licenciatura en Música, Nutrición y dietética, etc.

## Propuesta
Revisar si es posible mejorar las recomendaciones del bot.

## Canal

- [ ] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by jcechavarri** [comment]
w

**Comment by PipoLiz** [comment]
Varias personas nos han mencionado este asunto de las recomendaciones. Por favor, tenerlo muy presente.

**Comment by acarril** [comment]
OK, lo estamos investigando. Esto debe suceder porque hay varios modelos de recomendación, y hay algunos que son "fully random", entonces puede entregar recomendaciones bien distintas de la carrera en la que se mostró interés. Si es el caso, podemos desactivar este modelo en particular.

Hacer cambios a los modelos de recomendación requiere cierto trabajo, y lo vamos a hacer una vez que el bot público sea lanzado. Entonces propongo que en el corto plazo este modelo no se utilice para el bot público, y en el largo plazo podemos re-pensar qué modelos utilizamos. Está bien @PipoLiz ?

**Comment by PipoLiz** [comment]
Hola. Si, estamos de acuerdo en desactivar por el momento el Fully Random, y revisar a posteriori con base en qué otro modelo se puede hacer recomendación.

Muchas gracias.
