### ISSUE TITLE
La opción "hola" para volver al inicio del flujo no funciona

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#19]
## Describe el problema
![image](https://user-images.githubusercontent.com/87825021/192636250-0adf9ed5-d539-460e-8e12-55acdeb8b229.png)

Junto a que la opción no funciona, hay que actualizar muchas veces para que se borre la pantalla y salga el inicio.

Lo ideal sería que cuando ocurra un problema inesperado no se borre el avance, pero cuando uno de F5 o equivalentes, si se renueve el flujo.

**Comment by jcechavarri** [comment]
Hola @PipoLiz! En cuanto a tus comentarios:

> la opción no funciona

Estamos agregando una opción para "escapar" del flujo.

> cuando uno de F5 o equivalentes, si se renueve el flujo.

Preferimos no hacer esto, ya que haría que un alumno pierda su conversación si tiene una conexión de internet inestable.

> hay que actualizar muchas veces para que se borre la pantalla y salga el inicio.

La forma de lograr esto es
1. Cerrando la ventana actual del bot y abriendo otra.
2. Escribiendo hola en el chat (habiendo solucionado el problema descrito anteriormente).

Por favor no cierres esta _issue_ hasta que esté resuelta. Muchas gracias!
