### ISSUE TITLE
Cambio al flujo después de dar la expectativa salarial. 

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#21]
## Contexto
![image](https://user-images.githubusercontent.com/87825021/192639405-2d693f9e-4c83-48db-9307-85bcadf5b6a8.png)

Hemos recibido varios comentarios respecto a la aparente desconexión de solicitar el salario esperado, e inmediatamente después presentar otras opciones de carrera -que en ocasiones se alejan de la preferencia expresada-.

Favor de tener presente este asunto para modificaciones del flujo.

**Comment by jcechavarri** [comment]
Hola @PipoLiz! Podrías aclarar a qué te refieres con
> aparente desconexión de solicitar el salario esperado

Qué es lo que hace parecer que el bot fue desconectado? Muchas gracias

**Comment by PipoLiz** [comment]
Son las opciones de carrera. Para este ejemplo, se expreso el interés en artes representativa, y luego les muestra entre otras, la opción de Tecnología Contable y Tributaria.
