### ISSUE TITLE
[BUG] El bot no permite llegar a carreras relacionadas con la gastronomía

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#24]
## Describe el problema
El bot no permite llegar a carreras relacionadas con la gastronomía. 

Tomando los programas del SNIES Público se puede ver hay varios programas relacionados con gastronomía. Algunos de ellos están Activos. 
![image](https://user-images.githubusercontent.com/87825021/193659408-bef671f6-9fa6-4d93-96c1-dc3843a4fc1f.png)

Se propone revisar el motor de búsqueda. 

## Canal

- [ ] Web (bot público)
- [x] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by acarril** [comment]
No logramos encontrar ningún problema. La base de programas que se sube a AWS tiene todos los programas / instituciones activos de SNIES, cosa que comprobamos recién. Al hacer la búsqueda para la fila destacada en el _screenshot_, encontramos el programa sin problemas.

Por favor indicar pasos exactos para reproducir el problema, o si ya fue resuelto, cerrar el issue.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/9773292/193897064-6045cfcf-a694-40b4-beed-cc3bf4c958ae.png">

**Comment by PipoLiz** [comment]
Ok, para esa institución específica. Pero mira, si uno escoge la opción "Se qué estudiar pero no se en donde" no te muestra el programa.

![image](https://user-images.githubusercontent.com/87825021/193945113-36b9483b-b928-4930-b5c1-f2007574f1bd.png)
