### ISSUE TITLE
Respuesta al estrato

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#26]
## Contexto
![image](https://user-images.githubusercontent.com/87825021/193698900-3f3a5d67-eac1-46d4-8eb1-1346c0a9d860.png)

Se sugiere dejar la opción de estrato igual 0 en caso de no saber.
 
## Canal

- [ ] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by acarril** [comment]
Relacionado con #27, respondido en https://github.com/ConsiliumBots/icfesbot-2022-issue-tracker/issues/27#issuecomment-1266996511

Sugiero consolidar ambos issues en uno solo.

**Comment by acarril** [comment]
Consolidado con #27; cerrando por duplicado.
