### ISSUE TITLE
Permitir avanzar sin Sisbén y/o estrato

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#27]
## Contexto
![image](https://user-images.githubusercontent.com/87825021/193699172-90057599-4561-44f6-ac1c-6a8566c256dd.png)
![image](https://user-images.githubusercontent.com/9773292/193835812-632ce01b-2e45-4528-a989-568d33a57750.png)

## Sugerencia
Permitir al usuario escribir 0 en caso de no saber su Sisbén o estrato, para poder avanzar sin entregarlo.

## Canal

- [ ] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by acarril** [comment]
En general estamos intentando evitar dar información poco personalizada. Si permitimos a un estudiante avanzar sin Sisbén, sin estrato, y sin puntaje Saber 11, entonces al final la oferta de créditos que le vamos a mostrar deja de ser personalizada, y es equivalente a la oferta completa de créditos.

Podemos discutir qué tan conveniente es esto o no, pero por el momento la decisión para el lanzamiento 1.0 es "forzar" al estudiante a ingresar esos datos, aunque no los sepa bien.

**Comment by PipoLiz** [comment]
Hola Álvaro. 

Consideramos que es importante tener presente que este bot público es para toda la ciudadanía, de manera tal que sería ideal una opción igual a cero para el caso en que no se sepa como responder en Saber11, Sisben y estrato; eso animaría al uso de la herramienta.

Normalmente la gente se sabe su estrato, pero no su sisben y puntaje (cuya escala de medición ha cambiado en el tiempo). Introducir estos cambios puede que no afecte la respuesta del estrato, pero si evitaría desanimar el uso por la respuesta forzada  de puntaje en Saber 11 y sisben, y evitaría recolectar información falsa.
