### ISSUE TITLE
Ser Pilo Paga no debería ser una opción de financiamiento

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#28]
## Contexto
![image](https://user-images.githubusercontent.com/87825021/193699311-87b47dae-7213-4ffa-8fd4-c45b01268e76.png)

El programa Ser Pilo Paga ya no está disponible. Junto a ello cunado se selecciona siempre arroja error. 

Sugerimos quitar la opción SPP.

## Canal

- [ ] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by acarril** [comment]
Lia lista de créditos que utilizamos actualmente fue validada por Germán Pulido de ICETEX, en mail del 18 de Agosto 2022. En dicho correo él confirma haber revisado y validado todas las líneas de crédito de pregrado, y esta incluye una línea relacionada a SPP.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/9773292/193829644-4eec3d1e-dcda-4e35-bbd7-5d83b0ae6714.png">

El problema puede ser el nombre de la línea. El nombre completo de la línea es "Estudiantes beneficiarios rezagados de programas con crédito condonable (Ser Pilo Paga)", que nosotros abreviamos a "Ser Pilo Paga". Todas las líneas las presentamos usando un nombre abreviado, por un tema de espacio en la interfaz. Quizás sería mejor agregar algo de que es para beneficiarios rezagados?

**Comment by PipoLiz** [comment]
Hola Álvaro. Revisando lo que nos cuentas, nos parece importante ponerle a la línea de crédito "Ser Pilo Paga - Rezagados", procurando así no llevar a confusiones. Otra opción podría ser "SPP - Rezagados".

**Comment by jcechavarri** [comment]
Comment update:

> PipoLiz: El bot muestra la línea de crédito Ser Pilo Paga; si no mal recordamos se llama en realidad Ser Pilo Paga rezagados. ¿Podríamos verificar en las bases disponibles?

@acarril

**Comment by acarril** [comment]
Confirmo que, a la fecha, "Ser Pilo Paga - Rezagados" sí es una línea de crédito que [existe en la página de Icetex](https://web.icetex.gov.co/es/-/ser-pilo-paga-rezagados-tu-pagas-el-0), por lo que la vamos a mantener. Sin embargo, acuso recibo de su comentario de que la línea debiese llamarse "Ser Pilo Paga - Rezagados", y hemos implementado ese cambio.
