### ISSUE TITLE
[BUG]  Flujo sin información

### ISSUE THREAD

**Issue by jcechavarri** [ConsiliumBots/icfesbot-2022-issue-tracker#3]
Por: @PipoLiz

## Describe el problema

En la siguiente imagen se ve que no hay más info, ¿está bien?
![image](https://user-images.githubusercontent.com/42159312/188501045-0096c4f7-0641-4542-b5d2-1e4e3e9b9fdf.png)

## Para reproducirlo

1. 
2. 
3. 
4. 
5. 

## Canal

- [x] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by jcechavarri** [comment]
Hola @PipoLiz! Esta información todavía no se encuentra disponible, dejaremos este problema abierto hasta que se implemente. Gracias por notarlo.

**Comment by PipoLiz** [comment]
Hola Juan. ¿ Ahí que opciones se dispondrían ?
