### ISSUE TITLE
[BUG] <problema>

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#30]
## Describe el problema

![image](https://user-images.githubusercontent.com/87825021/193700797-66844f23-cf33-4061-95ba-eec509049752.png)

Según como se muestra en la imagen, la opción "hola" para volver al inicio, no funciona.

## Canal

- [ ] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by jcechavarri** [comment]
La opción hola se desactiva cuando se le pide al usuario ingresar texto. Para mayor claridad se agregó un mensaje en dichos casos.
