### ISSUE TITLE
[BUG] se repite el flujo para acceder a información de financiamiento

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#32]
## Describe el problema
![image](https://user-images.githubusercontent.com/87825021/193701427-a7050d7b-c128-4e7b-95f9-c961bc5f77f0.png)

Según se muestra en la imagen, el flujo del bot se repite después de que se pregunta el sisben. De hecho, en la imagen no se ve pero era la 4 vez que se repitió lo mismo. Pusimos las mismas opciones las 4 veces.

## Canal

- [x] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by jcechavarri** [comment]
Actualmente, no se puede continuar por el flujo de información financiera sin estrato o sisbén. El comando 0 es para volver al menú anterior, que es el comportamiento actual. Se agrega un mensaje explicando este comportamiento.
