### ISSUE TITLE
[FEAT] <Mejora en recomendaciónes>

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#34]
## Contexto

![image](https://user-images.githubusercontent.com/87825021/193939181-896ba15c-2af5-4fdf-a269-c417d73fc68a.png)

El motor de carrera puede seguir descalibrado ¿cuál es el sentido de recomendar derecho si se desea formación técnica profesional en Bellas Artes? 

## Canal

- [ ] Web (bot público)
- [ ] WhatsApp (bot público)
- [ ] Web (bot privado)
- [ ] WhatsApp (bot privado)

**Comment by jcechavarri** [comment]
Duplicada de #2
