### ISSUE TITLE
Líneas de crédito

### ISSUE THREAD

**Issue by PipoLiz** [ConsiliumBots/icfesbot-2022-issue-tracker#39]
### Canal

- [X] Whatsapp
- [ ] Web

### Describe el problema

El bot muestra la línea de crédito Ser Pilo Paga; si no mal recordamos se llama en realidad Ser Pilo Paga rezagados. ¿Podríamos verificar en las bases disponibles? Junto a ello, luego de solicitar información de la línea de crédito Volvamos a clases se genera un bug inesperado, ¿podríamos verificar por qué sale ese error? También, en el mensaje "Algo pasó..." tal como se muestra más adelante, falta la tilde en pasó. 

### Para reproducirlo

1. 
2. 
3. 
...

### Comportamiento esperado

Verificar nombres de las líneas de crédito. 
Verificar si es normal el bug en la línea de crédito Volvamos a clases. 
Revisar el mensaje del bug "Algo paso, por favor intenta de nuevo". Ya que falta una tilde. 
También en este a diferencia de la versión web, no se encuentra el botón de volver al inicio ¿es posible tenerlo en esta versión del wapp?

### Screenshots

![image](https://user-images.githubusercontent.com/87825021/199123420-e9bbfec5-12d8-4553-9337-bb502ed408eb.png)
![image](https://user-images.githubusercontent.com/87825021/199123854-903ee9de-a84d-4893-955d-132d446c9b55.png)

**Comment by jcechavarri** [comment]
Se dividió este BUG en un listado de issues correspondientes a lo mencionado.

#41 : Verificar nombres de las líneas de crédito.

#42 : Verificar si es normal el bug en la línea de crédito Volvamos a clases.

#43 : Revisar el mensaje del bug "Algo paso, por favor intenta de nuevo". Ya que falta una tilde.

#44 : no se encuentra el botón de volver al inicio ¿es posible tenerlo en esta versión del wapp?
