### ISSUE TITLE
Descripción de WhatsApp en inglés

### ISSUE THREAD

**Issue by jcechavarri** [ConsiliumBots/icfesbot-2022-issue-tracker#45]
### Canal

- [X] Whatsapp
- [ ] Web

### Describe el problema

El bot tiene una palabra en inglés dentro de su descripción:

> Explora tu futuro by ConsiliumBots

### Comportamiento esperado

Opciones:
- Explora tu futuro por ConsiliumBots
- Herramienta desarrollada por ConsiliumBots

### Screenshots

![WhatsApp Image 2022-11-01 at 11 46 32 AM](https://user-images.githubusercontent.com/42159312/199489188-9a2d5325-72aa-4f82-932e-c96e12758b50.jpeg)

**Comment by jcechavarri** [comment]
Se emitió una solicitud al proveedor de WhatsApp para realizar el cambio.

**Comment by acarril** [comment]
Me parece que esto ya se resolvió al momento que implementamos el nuevo número con código de país de Colombia.

![image](https://user-images.githubusercontent.com/9773292/201152416-dd6a4254-7a65-4c89-8ed1-9e4deed8acb7.png)
